import type { RegistryItem } from "./types";

/**
 * The catalogue Conduit ships with.
 *
 * A store whose first screen is "could not reach the registry" has taught the
 * user that the feature does not work, and they will not come back to it. So
 * the well-known servers and a handful of real skills are compiled in, and the
 * GitHub registry adds to them rather than being the only source. Entries are
 * marked so nobody has to guess which is which.
 *
 * Every command here is shown to the user before anything is launched. `npx`
 * fetches and runs a package from the network, which is exactly the kind of
 * thing that should be read before it is approved rather than after.
 */
export const BUILTIN_CATALOG: RegistryItem[] = [
  {
    id: "mcp-filesystem",
    icon: "folder",
    tint: "sun",
    kind: "mcp",
    name: "Filesystem",
    summary: "Reads and writes inside folders you name, with its own path checks.",
    author: "Model Context Protocol",
    version: "latest",
    license: "MIT",
    homepage: "https://github.com/modelcontextprotocol/servers",
    tags: ["files", "official"],
    builtin: true,
    mcp: {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-filesystem", "~/Documents"],
      note: "Change the last argument to the folder you want it to see. It can read and write anywhere below that path.",
    },
  },
  {
    id: "mcp-github",
    icon: "branch",
    tint: "ink",
    featured: true,
    kind: "mcp",
    name: "GitHub",
    summary: "Issues, pull requests, code search and file contents across your repositories.",
    author: "Model Context Protocol",
    version: "latest",
    license: "MIT",
    homepage: "https://github.com/modelcontextprotocol/servers",
    tags: ["development", "git", "official"],
    builtin: true,
    mcp: {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-github"],
      env: [
        {
          name: "GITHUB_PERSONAL_ACCESS_TOKEN",
          secret: "mcp-github",
          label: "GitHub token",
          help: "A personal access token with the scopes you want it to have. Stored in your OS credential store.",
        },
      ],
    },
  },
  {
    id: "mcp-memory",
    icon: "nodes",
    tint: "grape",
    kind: "mcp",
    name: "Memory",
    summary: "A knowledge graph the agent can write to and read back in later conversations.",
    author: "Model Context Protocol",
    version: "latest",
    license: "MIT",
    homepage: "https://github.com/modelcontextprotocol/servers",
    tags: ["memory", "official"],
    builtin: true,
    mcp: { command: "npx", args: ["-y", "@modelcontextprotocol/server-memory"] },
  },
  {
    id: "mcp-sequential-thinking",
    icon: "steps",
    tint: "sky",
    kind: "mcp",
    name: "Sequential thinking",
    summary: "A scratchpad for working a hard problem through in steps.",
    author: "Model Context Protocol",
    version: "latest",
    license: "MIT",
    homepage: "https://github.com/modelcontextprotocol/servers",
    tags: ["reasoning", "official"],
    builtin: true,
    mcp: { command: "npx", args: ["-y", "@modelcontextprotocol/server-sequential-thinking"] },
  },
  {
    id: "mcp-playwright",
    icon: "browser",
    tint: "lime",
    featured: true,
    kind: "mcp",
    name: "Playwright",
    summary: "Drives a real browser through its accessibility tree. Faster and steadier than screen control for anything on the web.",
    author: "Microsoft",
    version: "latest",
    license: "Apache-2.0",
    homepage: "https://github.com/microsoft/playwright-mcp",
    tags: ["browser", "testing"],
    builtin: true,
    mcp: {
      command: "npx",
      args: ["-y", "@playwright/mcp@latest"],
      note: "Downloads a browser the first time it runs.",
    },
  },
  {
    id: "mcp-context7",
    icon: "book",
    tint: "ocean",
    kind: "mcp",
    name: "Context7",
    summary: "Current documentation for libraries, fetched at the version you are actually using.",
    author: "Upstash",
    version: "latest",
    license: "MIT",
    homepage: "https://github.com/upstash/context7",
    tags: ["docs", "development"],
    builtin: true,
    mcp: { command: "npx", args: ["-y", "@upstash/context7-mcp"] },
  },

  // --- skills ---------------------------------------------------------------

  {
    id: "skill-review",
    icon: "review",
    tint: "mint",
    featured: true,
    kind: "skill",
    name: "Change review",
    summary: "Reads a diff for defects that would actually bite, and says what would break.",
    author: "Conduit",
    version: "1.0.0",
    license: "MIT",
    tags: ["development"],
    builtin: true,
    content: {
      "SKILL.md": [
        "---",
        "name: change-review",
        "description: Review a diff or a set of edits for defects. Use when asked to review, check, or sanity-check a change before it ships.",
        "---",
        "",
        "# Reviewing a change",
        "",
        "Read the whole diff before saying anything. A review that comments on the",
        "first hunk and stops is worse than no review, because it reads as complete.",
        "",
        "## What counts as a finding",
        "",
        "Something that produces wrong behaviour, loses data, or breaks for a real",
        "input. For each one, give the concrete case: the input or state, and the",
        "wrong result it leads to. If you cannot name that case, it is a preference,",
        "not a finding — say so or leave it out.",
        "",
        "## Order of attention",
        "",
        "1. **Correctness at the boundaries.** Empty, one, many. Zero, negative,",
        "   overflow. Absent, null, malformed. Most defects live here.",
        "2. **Error paths.** What happens when the call fails, the file is missing,",
        "   the user declines. Silent swallowing is a defect even when nothing",
        "   visibly breaks.",
        "3. **Concurrency and ordering.** Anything awaiting inside a loop over shared",
        "   state, or assuming two events arrive in the order they were sent.",
        "4. **Resource lifetime.** Listeners, timers, watchers, child processes,",
        "   file handles. Check that every one has a path that releases it.",
        "5. **The claim the code makes.** If a comment or a name promises something",
        "   the body does not do, one of the two is wrong.",
        "",
        "## What to skip",
        "",
        "Formatting, naming preferences, and rewrites that trade one working shape",
        "for another. They crowd out the findings that matter.",
        "",
        "## Reporting",
        "",
        "Most severe first. One line for the defect, one for the failing case, then",
        "the fix if it is short. End with what you checked and found clean, so the",
        "reader knows the scope rather than assuming it.",
      ].join("\n"),
    },
  },
  {
    id: "skill-commit",
    icon: "commit",
    tint: "ember",
    kind: "skill",
    name: "Commit messages",
    summary: "Writes the message from what the diff actually does, not from the file names.",
    author: "Conduit",
    version: "1.0.0",
    license: "MIT",
    tags: ["development", "git"],
    builtin: true,
    content: {
      "SKILL.md": [
        "---",
        "name: commit-message",
        "description: Write a commit message for staged changes. Use when asked to commit, or to write or improve a commit message.",
        "---",
        "",
        "# Writing a commit message",
        "",
        "Read the diff first — `git diff --cached`, and `git log -12 --oneline` to",
        "match the repository's existing register. A message written from the file",
        "list describes the edit; a message written from the diff describes the",
        "change, and only the second is worth reading in six months.",
        "",
        "## The subject",
        "",
        "One line, imperative, under about 70 characters, no trailing full stop.",
        "It names what the change does, not where it happened. `Fix off-by-one in",
        "pagination`, not `Update utils.ts`.",
        "",
        "## The body",
        "",
        "Only when the subject leaves a real question. Answer *why*: the behaviour",
        "that was wrong, the constraint that forced this shape, the thing a reader",
        "would otherwise try to \"fix\" back. Never restate the diff — the diff is",
        "already attached.",
        "",
        "## Rules",
        "",
        "- One change per commit. If the diff does two things, say so and offer to",
        "  split it rather than writing a message with an \"and\" in it.",
        "- Match the repository's convention if it has one (Conventional Commits,",
        "  a ticket prefix, a subsystem tag). Look, do not assume.",
        "- Never claim a test passed unless you ran it.",
      ].join("\n"),
    },
  },
  {
    id: "skill-onboard",
    icon: "map",
    tint: "sky",
    kind: "skill",
    name: "Learn a codebase",
    summary: "A route into an unfamiliar repository that starts with what runs, not with the folder tree.",
    author: "Conduit",
    version: "1.0.0",
    license: "MIT",
    tags: ["development"],
    builtin: true,
    content: {
      "SKILL.md": [
        "---",
        "name: learn-codebase",
        "description: Get oriented in an unfamiliar repository. Use when asked what a project does, how it is structured, or where to change something.",
        "---",
        "",
        "# Getting into a codebase",
        "",
        "Start where the program starts, not at the top of the folder tree. A",
        "directory listing tells you what somebody filed; an entry point tells you",
        "what actually runs.",
        "",
        "## The route",
        "",
        "1. **Manifest.** `package.json`, `Cargo.toml`, `pyproject.toml`. The scripts",
        "   say how it is built, run and tested. The dependencies say what kind of",
        "   program it is.",
        "2. **Entry point.** Follow `main`, the server bootstrap, the root component.",
        "   Read it end to end.",
        "3. **One real path.** Pick something the program does and trace it from the",
        "   outside in. One complete path teaches more than ten files skimmed.",
        "4. **The seams.** Where does it touch the network, the disk, the database?",
        "   Those are the boundaries everything else is arranged around.",
        "5. **Tests.** The test names are a specification somebody actually checked.",
        "",
        "## Reporting back",
        "",
        "Say what the program is for in one sentence. Then the three or four places",
        "a newcomer would need to know about, each with why it matters. Name the",
        "surprises — the thing that is not where you would expect it — because that",
        "is what costs an afternoon.",
        "",
        "Be explicit about what you did not read.",
      ].join("\n"),
    },
  },
  {
    id: "skill-debug",
    icon: "bug",
    tint: "rose",
    kind: "skill",
    name: "Debug from a symptom",
    summary: "Narrows a bug by bisecting what is true, instead of guessing at causes.",
    author: "Conduit",
    version: "1.0.0",
    license: "MIT",
    tags: ["development"],
    builtin: true,
    content: {
      "SKILL.md": [
        "---",
        "name: debug-symptom",
        "description: Track down a bug from an error message or a wrong behaviour. Use when something fails and the cause is not obvious.",
        "---",
        "",
        "# Debugging",
        "",
        "The failure is a fact. Everything else is a hypothesis, and the job is to",
        "cut the space of hypotheses in half at every step rather than to guess well.",
        "",
        "## Steps",
        "",
        "1. **Reproduce it.** If you cannot make it happen on demand, you cannot",
        "   know when you have fixed it. Get to a single command that fails.",
        "2. **Read the whole error.** The first line names the symptom; the frame",
        "   that matters is usually further down, in code somebody here wrote.",
        "3. **Find the last point where things were right.** Print, log or break",
        "   half way along the path. Move the probe, not the theory.",
        "4. **Change one thing.** Two changes and a fix tells you nothing about",
        "   which one worked.",
        "5. **Explain the mechanism before fixing.** If you cannot say why the bug",
        "   produced exactly this symptom, you have found *a* problem, not *the*",
        "   problem — and the fix will come back.",
        "",
        "## Traps",
        "",
        "- An exit code of zero from a pipeline is the last command's, not the",
        "  first's. Check the one you meant.",
        "- \"It works now\" after an unrelated change usually means a race.",
        "- A stale build, a cached module or an old process explains a startling",
        "  number of impossible symptoms. Rule those out early and cheaply.",
        "",
        "Finish by stating the mechanism in one sentence, and what you did to",
        "confirm the fix.",
      ].join("\n"),
    },
  },
];
